### PR TITLE
Natural text dataset elsevier_oa_cc-by_corpus

### PR DESCRIPTION
**Pull request by MicPie**

### CODE REVIEW

**Review by kjappelbaum — APPROVED** [review]
nice num points are here the articles?

**Comment by MicPie** [comment]
@kjappelbaum Oh, the number of points are the number of lines in the jsonl file, in this case it is the number of articles with an abstract. I'm currently only getting the abstract because I need to check in detail on how to get the entire publication text nicely.

**Comment by MicPie** [comment]
This dataset is also on the HF Hub: https://huggingface.co/datasets/orieg/elsevier-oa-cc-by

**Comment by MicPie** [comment]
PR now includes more data, see example below:
```Title
Biological carbon dioxide utilisation in food waste anaerobic digesters

Subject Classification
ENVI

All Science Journal Classification
2302, 2310, 2311, 2312

Keywords
Anaerobic digestion, Bubble column, Carbon dioxide utilisation, Food waste, Hydrogen,

Abstract
Carbon dioxide (CO2) enrichment of anaerobic digesters (AD) was previously identified as a potential on-site carbon revalorisation strategy. This study addresses the lack of studies investigating this concept in up-scaled units and the need to understand the mechanisms of exogenous CO2 utilisation. Two pilot-scale ADs treating food waste were monitored for 225 days, with the test unit being periodically injected with CO2 using a bubble column. The test AD maintained a CH4 production rate of 0.56 ± 0.13 m3 CH4·(kg VSfed d)-1 and a CH4 concentration in biogas of 68% even when dissolved CO2 levels were increased by a 3 fold over the control unit. An additional uptake of 0.55 kg of exogenous CO2 was achieved in the test AD during the trial period. A 2.5 fold increase in hydrogen (H2) concentration was observed and attributed to CO2 dissolution and to an alteration of the acidogenesis and acetogenesis pathways. A hypothesis for conversion of exogenous CO2 has been proposed, which requires validation by microbial community analysis.

Author Highlights
1.) Utilisation of exogenous CO2 in ADs was investigated.
2.) A pilot-scale AD with CO2 injection treating food waste operated for the first time.
3.) Injection of CO2 with a bubble column achieved without diluting the AD's headspace.
4.) Concentration of H2 increased by 2.5 fold after four CO2 injections.
5.) A mechanism of CO2 utilisation has been proposed.


Introduction
Anaerobic digestion (AD) stabilises organic wastes while producing biogas with a 50–75% methane (CH4) and 50–25% carbon dioxide (CO2) concentration. The calorific value of the biogas can then be used by combustion in combined heat and power (CHP) engines or by selectively separating the CH4 for its use as biomethane. The remaining CO2 present in the biogas, however, is emitted to the atmosphere with exhaust gas streams. Biogenic emissions of CO2 from ADs just in the UK have been estimated at 0.27 MtCO2 per annum for the water sector (Byrns et al., 2013) and at 0.31 MtCO2 per annum for ADs treating agricultural and community waste (industrial sites not accounted) (Bajón Fernández et al., Submitted for publication a). Emissions of CO2 with biogenic origin are not considered within carbon accounting inventories, however,```

**Comment by MicPie** [comment]
Ok, now with markdown:
> # Title
Effects of carbon supports on Pt distribution, ionomer coverage and cathode performance for polymer electrolyte fuel cells

# Subject Classification
CHEM, ENER, ENGI

# All Science Journal Classification
1606, 2102, 2105, 2208

# Keywords
Carbon-supported Pt catalysts, Effective Pt surface area, Ionomer distribution, Polymer electrolyte fuel cells, Pore structure,

# Abstract
We investigate the effects of the carbon supports on the Pt distribution, ionomer coverage and cathode performance of carbon-supported Pt catalysts, by using STEM observation, N2 adsorption analysis and electrochemical characterization. According to the STEM observation, the effective Pt surface area (S(e)Pt), which is determined by the location and size of the Pt particles on the supports, increases in the following order: c-Pt/CB < c-Pt/GCB < n-Pt/AB800 < n-Pt/AB250. The N2 adsorption analyses show that the Pt particles observed in the interior of the CB and AB800-supported Pt catalysts during the STEM observation could be ascribed to the hollow structures inside the carbon supports, which decrease their effective Pt surface areas. The S(e)Pt values are in good agreement with the cell performance in the high current density region. In spite of the highest Pt utilization (UPt) value (>90%) and uniform ionomer coverage, the c-Pt/CB catalyst shows the lowest cell performance due to the lower S(e)Pt value. On the other hand, the n-Pt/AB250 catalyst, for which all of the Pt particles exist only on the exterior surface, is found to be the most attractive in order to generate the large current densities required by actual fuel cell operation.

# Author Highlights
1. Effective Pt surface area was in the order: Pt/CB < Pt/GCB < Pt/AB800 < Pt/AB250.
2. Hollow structure of the CB and AB800 decreased the effective Pt surface area (S(e)Pt).
3. S(e)Pt values were in good agreement with the performance at high current densities.
4. This is due to improvement of the effective Pt surface area and ionomer distribution.
5. The AB-supported Pt catalysts had well-balanced supply paths for protons and oxygen.


# Introduction
The polymer electrolyte fuel cell (PEFC) is one of the most attractive power generation systems for fuel cell vehicles (FCVs) and residential co-generation systems, due to its low level of exhaust emissions and high energy efficiency. ...

**Pull request merged**
