### PR TITLE
feat: add RedDB

### PR DESCRIPTION
**Pull request by AdrianM0**
Add dataset:  https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/F3QFSQ

### CODE REVIEW

**Comment by kjappelbaum** [comment]
for the absolute energies (e.g. HOMO/LUMO): do you think we still should mention the computational techniques?

**Comment by AdrianM0** [comment]
> for the absolute energies (e.g. HOMO/LUMO): do you think we still should mention the computational techniques?

yeah, that is certainly a good idea, will add now

**Comment by kjappelbaum** [comment]
it looks overall very good! Nice! 💯 

will check out in a few minutes and run the sampling as I find it easier to spot things in text than in the templates

**Comment by kjappelbaum** [comment]
Screenshot 2023-10-17 at 14 42 15
nice!

**Comment by kjappelbaum** [comment]
and, I think, the reaction field energy would need specification of the solvent (?)

**Comment by kjappelbaum** [comment]
as do the energies in solution

**Comment by kjappelbaum** [comment]
@AdrianM0, if it is still okay for you now, I'd merge it! Thanks for this addition!

**Comment by AdrianM0** [comment]
> @AdrianM0, if it is still okay for you now, I'd merge it! Thanks for this addition!

all good 👍 i will avoid the ML descriptors in the future!

**Pull request merged**
