### PR TITLE
Consider adding URIs for dataset targets and properties

### LINKED ISSUE #73: Consider adding URIs for dataset targets and properties
(related to #72)

The idea is that these URIs can at least i) resolve whether two definitions are the same across datasets and could potentially ii) be used to augment the dataset with canonical descriptions and semantic links, either during prep or by the model on-the-fly.

This currently assumes an "exact match" style mapping between target and property -- we could build in additional semantic context in the schema here to enable things like related identities/subclasses/parthood and all that jazz. I struggled with the Butkiewicz sets as it is really outside my field and definitions are available for e.g., cav3, t-type, calcium channel and activity but not activity_cav3_t_type_calcium_channels.

As discussed, this is quite a niche task that may not be suitable to ask others to perform. Even in my own case, it is not clear exactly how good these particular definitions are -- I just went via BioPortal for fields that have good matches: https://bioportal.bioontology.org/

*originally posted in https://github.com/OpenBioML/chemnlp/pull/72#issue-1613924718*

### PR DESCRIPTION
**Pull request by kjappelbaum**
Fixes #73

Co-authored-by: Matthew Evans <7916000+ml-evs@users.noreply.github.com>

### CODE REVIEW

**Comment by kjappelbaum** [comment]
opened as follow up from #72

**Comment by ml-evs** [comment]
weird, you should have the rights:

image

**Comment by ml-evs** [comment]
Just explicitly invited you in case that is easier, also happy to have two separate PRs, up to you!

**Comment by kjappelbaum** [comment]
>Just explicitly invited you in case that is easier, also happy to have two separate PRs, up to you! 

you did the work, so really up to you! I can try again on your PR :D

**Pull request closed without merging**
