### PR TITLE
feat: implement benchmark field 2

### PR DESCRIPTION
**Pull request by MicPie**
New PR based on PR https://github.com/OpenBioML/chemnlp/pull/116 and issue https://github.com/OpenBioML/chemnlp/issues/115 due to updated `main` branch.
PR https://github.com/OpenBioML/chemnlp/pull/116 will be closed when this PR is finished.

### CODE REVIEW

**Comment by jackapbutler** [comment]
Hey @MicPie, for this use case of #108 will we continue to use `split_col` going forward but this denotes the split of the dataset not split in benchmarks?

**Comment by kjappelbaum** [comment]
>Hey @MicPie, for this use case of #108 will we continue to use split_col going forward but this denotes the split of the dataset not split in benchmarks?

I think the `meta.yaml` are not supposed to say anything about the split we will use yet. The only thing we try to capture is what molecules have been part of a test set such that we might be able to also put them into our test set. Hence, I think this benchmark field is good enough for now (?)

**Comment by kjappelbaum** [comment]
@MicPie should I commit the fix for the `403` error directly to your PR?

**Comment by MicPie** [comment]
> @MicPie should I commit the fix for the 403 error directly to your PR?
@kjappelbaum Yes, please, feel free to add to this branch.

**Comment by MicPie** [comment]
> Ah cool, so if we find one with some existing train/val/test splits should we recombine it into one for uploading?

@jackapbutler Yes, I would go for that. With that we can still filter it down later depending on our benchmarking setup.

**Review by kjappelbaum — APPROVED** [review]
If the checks pass now, it is OK to merge for me. Thanks! 💯

**Pull request merged**
