### PR TITLE
Adding odd-one-out dataset

### PR DESCRIPTION
**Pull request by Pixelatory**
Creating the odd-one-out dataset, for an example application such as below:
"Q: Which molecule is the least similar to the others?

1. [Mol 1]
2. [Mol 2]
3. [Mol 3]
4. [Mol 4]

A: [Answer]"

Uses the ChEMBLv29 dataset (retrieved from therapeutic commons) with Tanimoto Similarity and Morgan Fingerprints implemented in RDKit, with radius 2.

### CODE REVIEW

**Comment by kjappelbaum** [comment]
looks cool, I'll try to run it and to prepare a `meta.yaml` file

**Comment by kjappelbaum** [comment]
just a comment for the future: it is often easier if you make pull requests from a new branch (i.e. not `main`)

**Comment by Pixelatory** [comment]
Sorry yes I forgot to make a new branch. I'll make sure to make one for next time.

**Review by MicPie — APPROVED** [review]
lgtm

**Pull request merged**
