### PR TITLE
New datasets for solubility and non-fouling activity of peptide sequences

### PR DESCRIPTION
**Pull request by mehradans92**

### CODE REVIEW

**Comment by kjappelbaum** [comment]
Thanks for adding them. Yes, the CI is currently failing (#390)

**Comment by kjappelbaum** [comment]
On a first look, the prompts look very cool, too! I'll try to run your code and then give you more detailed feedback.

**Comment by kjappelbaum** [comment]
Hi! I updated templates to better-sounding/more meaningful prompts. 

Thanks a lot for this addition, since to also have amino acids!

**Review by kjappelbaum — APPROVED** [review]

**Comment by mehradans92** [comment]
Thanks @kjappelbaum  :)

**Pull request merged**
