### PR TITLE
feat: add structured data handling example

### PR DESCRIPTION
**Pull request by MicPie**
PR for issue https://github.com/OpenBioML/chemnlp/issues/3

### CODE REVIEW

**Comment by MicPie** [comment]
@kjappelbaum updated PR based on https://github.com/OpenBioML/chemnlp/pull/6

**Comment by kjappelbaum** [comment]
ok, will update the contribution guide saying that also notebooks are ok

**Comment by kjappelbaum** [comment]
Let me quickly create a GitHub action that validates the `yaml` files.

**Comment by kjappelbaum** [comment]
We should decide whether to allow anything for raw -> processed csv or ask for one `transform.py` file. If the latter, we should also update this PR.

**Comment by kjappelbaum** [comment]
(And also update the slides, which currently mention a `transform.py` file)

**Comment by MicPie** [comment]
@kjappelbaum I adapted the notebook and added the `transform.py` file. Please test too.

**Pull request merged**
